// This file was autogenerated by /home/mathieu/Workspace/go/src/github.com/MathieuTurcotte/go-browserchannel/test/../closure-library/closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../../index.js', ['tests.start'], ['goog.debug.Console', 'goog.net.BrowserChannel', 'goog.net.ChannelDebug', 'tests.Handler1']);
goog.addDependency('../../../tests/case1.js', ['tests.Handler1'], ['goog.Timer', 'goog.debug.Logger', 'goog.net.BrowserChannel.Handler']);
