language: go

before_script:
    - start-stop-daemon --start --quiet --background --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --exec go --
        run src/github.com/MathieuTurcotte/go-browserchannel/test/server/server.go
            --public_directory=src/github.com/MathieuTurcotte/go-browserchannel/test/client
            --closure_directory=src/github.com/MathieuTurcotte/go-browserchannel/closure-library
            --port=8080

script:
    - go test -v github.com/MathieuTurcotte/go-browserchannel/browserchannel/...
    - phantomjs src/github.com/MathieuTurcotte/go-browserchannel/test/runner.js
